FROM golang:1.26.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/billing-service ./cmd/billing-service

FROM alpine:3.22

WORKDIR /app
COPY --from=builder /bin/billing-service /usr/local/bin/billing-service

EXPOSE 8082

CMD ["billing-service"]

